<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DrinkProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            ['code' => '101', 'name' => 'BOTELLA Budweiser 710 x6'],
            ['code' => '102', 'name' => 'BOTELLA Stella 710cc X6'],
            ['code' => '103', 'name' => 'BARRIL Heineken x1'],
            ['code' => '104', 'name' => 'Lata 410cc Patagonia BOHEMIAN x24'],
            ['code' => '105', 'name' => 'Lata 473cc Patagonia VERA IPA x24'],
            ['code' => '106', 'name' => 'Lata 473cc Patagonia Travesia Sureña  x24'],
            ['code' => '107', 'name' => 'Lata 473cc Patagonia 24.7 IPA x24'],
            ['code' => '108', 'name' => 'Lata 410cc Patagonia  AMBER x24'],
            ['code' => '109', 'name' => 'Lata 473cc Patagonia WEISSE  x24'],
            ['code' => '110', 'name' => 'Lata 473cc Antares Lager x24'],
            ['code' => '111', 'name' => 'Lata 410cc Corona  x24'],
            ['code' => '112', 'name' => 'Lata 473cc Grolsch x24'],
            ['code' => '113', 'name' => 'Lata 473cc Imperial x 24'],
            ['code' => '114', 'name' => 'Lata 473cc Imperial APA  x 24'],
            ['code' => '115', 'name' => 'Lata 473cc Imperial Golden x 24'],
            ['code' => '116', 'name' => 'Lata 473cc Imperial IPA x 24'],
            ['code' => '117', 'name' => 'Lata 473cc Imperial ROJA x 24'],
            ['code' => '118', 'name' => 'Lata 473cc Imperial Negra  x 24'],
            ['code' => '119', 'name' => 'Lata 473cc Schenaider x 24'],
            ['code' => '120', 'name' => 'Lata 473cc Stella Artois  x24'],
            ['code' => '121', 'name' => 'Lata 473cc Stella Artois  Negra x24'],
            ['code' => '122', 'name' => 'Lata 473cc Miller x 24'],
            ['code' => '123', 'name' => 'Lata 473cc Warsteiner x 24'],
            ['code' => '124', 'name' => 'Lata 473cc Brahma  x24'],
            ['code' => '125', 'name' => 'Lata 473cc Brahma Dorada x24'],
            ['code' => '126', 'name' => 'Lata 473cc Quilmes  x 24'],
            ['code' => '127', 'name' => 'Lata 473cc Quilmes IPA x 24'],
            ['code' => '128', 'name' => 'Lata 473cc Quilmes Red Lager x 24'],
            ['code' => '129', 'name' => 'Lata 473cc Quilmes 0.0 x 24'],
            ['code' => '130', 'name' => 'Lata 473cc Quilmes Stout x 24'],
            ['code' => '131', 'name' => 'Lata 473cc Andes Blanca x 24'],
            ['code' => '132', 'name' => 'Lata 473cc Andes Negra x 24'],
            ['code' => '133', 'name' => 'Lata 473cc Andes Ipa x 24'],
            ['code' => '134', 'name' => 'Lata 473cc Andes Rubia x 24'],
            ['code' => '135', 'name' => 'Lata 473cc Andes Rubia ORO x 24'],
            ['code' => '136', 'name' => 'Lata 473cc Andes  Roja x 24'],
            ['code' => '137', 'name' => 'Lata 473cc  Budweiser x 24'],
            ['code' => '138', 'name' => 'Lata 473cc Heineken x 24'],
            ['code' => '139', 'name' => 'Lata 473cc Isembeck x 24'],
            ['code' => '140', 'name' => 'Lata 473cc Amstel x 24'],
            ['code' => '141', 'name' => 'LATON AMSTEL x 24'],
            ['code' => '142', 'name' => 'LATON Miller 710cc x 24'],
            ['code' => '143', 'name' => 'LATON Imperial 710cc x 24'],
            ['code' => '144', 'name' => 'LATON Imperial Golden 710cc x 24'],
            ['code' => '145', 'name' => 'LATON Budweiser 710cc x 16'],
            ['code' => '146', 'name' => 'LATON Schenaider 710cc x 24'],
            ['code' => '147', 'name' => 'LATON Quilmes 710cc x 16'],
            ['code' => '148', 'name' => 'LATON Brahma 710cc x 16'],
            ['code' => '149', 'name' => 'LATON Heineken 710cc x 24'],
            ['code' => '150', 'name' => 'Corona 710cc x 12'],
            ['code' => '151', 'name' => 'Porron Corona x 24'],
            ['code' => '152', 'name' => 'Porron Corona CERO x 24'],
            ['code' => '153', 'name' => '2250cc Pepsi x 8'],
            ['code' => '154', 'name' => '2250cc 7up x 8'],
            ['code' => '155', 'name' => '2250cc 7up free x 8'],
            ['code' => '156', 'name' => '2250cc Mirinda Naranja x 8'],
            ['code' => '157', 'name' => '2000cc PEPSI 2000CC X 8'],
            ['code' => '158', 'name' => '2000cc 7UP 2000CC X 8'],
            ['code' => '159', 'name' => '2000cc 7UP FREE 2000CC X 8'],
            ['code' => '160', 'name' => '2000cc PEPSI BLACK 2000CC X 8'],
            ['code' => '161', 'name' => '1500cc Pepsi 1500cc x 6'],
            ['code' => '162', 'name' => '1500cc 7up 1500cc x 6'],
            ['code' => '163', 'name' => '1500cc 7up free 1500cc x 6'],
            ['code' => '164', 'name' => '1500cc Pepsi LIGHT  x 6'],
            ['code' => '165', 'name' => '1500cc Pepsi Black x 6'],
            ['code' => '166', 'name' => '1500cc PDT Pomelo regular x 6'],
            ['code' => '167', 'name' => '1500cc PDT Tonica x 6'],
            ['code' => '168', 'name' => '1500cc PDT Pomelo light x 6'],
            ['code' => '169', 'name' => '2000cc PEPSI 2000CC X 8 (DESCARTABLE)'],
            ['code' => '170', 'name' => 'Lata Pepsi 354cc x 24'],
            ['code' => '171', 'name' => 'Lata 7up 354cc x 24'],
            ['code' => '172', 'name' => 'Pet 500 Pepsi x 12'],
            ['code' => '173', 'name' => 'Pet 500 7up x 12'],
            ['code' => '174', 'name' => 'LATA Pepsi TWIST 354cc x 24'],
            ['code' => '175', 'name' => 'LATA Pepsi BLACK 354cc x 24'],
            ['code' => '176', 'name' => 'Lata Pdt Tonica 269cc x 24'],
            ['code' => '177', 'name' => 'Coca Cola 2250 x 8'],
            ['code' => '178', 'name' => 'Coca cola Light 2250 x 8'],
            ['code' => '179', 'name' => 'Coca Cola Zero 2250 x 8'],
            ['code' => '180', 'name' => 'Sprite 2250 x 8'],
            ['code' => '181', 'name' => 'Sprite Zero 2250 x 8'],
            ['code' => '182', 'name' => 'Fanta 2250 x 8'],
            ['code' => '183', 'name' => 'Coca cola 1750 x8'],
            ['code' => '184', 'name' => 'Coca Light 1750 x 8'],
            ['code' => '185', 'name' => 'Coca Zero 1750 x 8'],
            ['code' => '186', 'name' => 'Sprite 1750cc x8'],
            ['code' => '187', 'name' => 'Fanta 1750cc x8'],
            ['code' => '188', 'name' => 'Coca Cola 2500cc x 6'],
            ['code' => '189', 'name' => 'Scheweppces Pomelo 1500cc x8'],
            ['code' => '190', 'name' => 'Scheweppces Tonica 1500cc x8'],
            ['code' => '191', 'name' => 'Scheweppces Pomelo  2250 cc x8'],
            ['code' => '192', 'name' => 'Scheweppces Tonica  2250 cc x8'],
            ['code' => '193', 'name' => 'Sprite 500cc x12'],
            ['code' => '194', 'name' => 'Lata Coca Cola 354 cc x 6'],
            ['code' => '195', 'name' => 'Lata Coca Cola Zero 354 cc x 6'],
            ['code' => '196', 'name' => 'Powerade 1.500cc x 4 Manzana'],
            ['code' => '197', 'name' => 'Powerade 995cc x 6 Blue'],
            ['code' => '198', 'name' => 'Gatorade Pet 1250cc Manzana x6'],
            ['code' => '199', 'name' => 'Gatorade Pet 1250cc Naranja x6'],
            ['code' => '200', 'name' => 'Gatorade Pet 1250cc Cool Blue x6'],
            ['code' => '201', 'name' => 'Gatorade Pet 1250cc Lima Limon'],
            ['code' => '202', 'name' => 'Gatorade Pet 1250cc Frutas Tropicales x6'],
            ['code' => '203', 'name' => 'Gatorade Pet 750cc Manzana x6'],
            ['code' => '204', 'name' => 'Gatorade Pet 500cc Manzana x6'],
            ['code' => '205', 'name' => 'Gatorade Pet 500cc Cool Blue x6'],
            ['code' => '206', 'name' => 'Gatorade Pet 500cc Frutas Tropicales x6'],
            ['code' => '207', 'name' => 'Gatorade Pet 500cc Uva x6'],
            ['code' => '208', 'name' => 'Cepita Naranja Tetra 1000cc x8'],
            ['code' => '209', 'name' => 'Cepita Manzana Tetra 1000cc x8'],
            ['code' => '210', 'name' => 'Jugo Ades Manzana 1000cc x 8'],
            ['code' => '211', 'name' => 'Jugo Ades Multifruta 1000cc x 8'],
            ['code' => '212', 'name' => 'Jugo Ades Naranja 1000cc x 8'],
            ['code' => '213', 'name' => 'Cepita Naranja Botella 1000cc x6'],
            ['code' => '214', 'name' => 'Cepita Durazno Botella 1000cc x6'],
            ['code' => '216', 'name' => 'Glaciar 2000cc sin Gas x 6'],
            ['code' => '217', 'name' => 'Glaciar 1500cc Sin Gas x 6'],
            ['code' => '218', 'name' => 'Glaciar 1500cc Con Gas x 6'],
            ['code' => '219', 'name' => 'Glaciar 500cc sin gas x 12'],
            ['code' => '220', 'name' => 'Glaciar GO 750cc sin gas x 6'],
            ['code' => '221', 'name' => 'Bidon Agua Benedictino 6 X2'],
            ['code' => '222', 'name' => 'Eco de los Andes 2000cc x 6'],
            ['code' => '223', 'name' => 'Eco de los Andes One 1L Sin gas x 6'],
            ['code' => '224', 'name' => 'Eco de los Andes 500cc x 12'],
            ['code' => '225', 'name' => 'Eco de los Andes 850cc x 6'],
            ['code' => '226', 'name' => 'Villavicencio 2000cc Sin gas x 6'],
            ['code' => '227', 'name' => 'Villavicencio sport 600cc x 12'],
            ['code' => '228', 'name' => 'Villavicencio 1500cc Con gas x 6'],
            ['code' => '229', 'name' => 'Villavicencio 500cc Sin gas x12'],
            ['code' => '230', 'name' => 'Villavicencio 500cc Con gas'],
            ['code' => '231', 'name' => 'Villa del sur 1650cc x6'],
            ['code' => '232', 'name' => 'Villa del sur 600cc Sin gas X12'],
            ['code' => '233', 'name' => 'Cerveza Goyeneche 500cc x6 Blonde ALE'],
            ['code' => '234', 'name' => 'Cerveza Goyeneche 500cc x6 GOLDEN'],
            ['code' => '235', 'name' => 'Cerveza Goyeneche 500cc x6 SCOTTISH'],
            ['code' => '236', 'name' => 'Cerveza Goyeneche 500cc x6 PORTER'],
            ['code' => '237', 'name' => 'Cerveza Goyeneche 500cc x6 HONEY'],
            ['code' => '238', 'name' => 'Cerveza Goyeneche 500cc x6 IPA'],
            ['code' => '239', 'name' => 'Levite 2250cc Pomelo x6'],
            ['code' => '240', 'name' => 'Levite 2250cc Naranja x6'],
            ['code' => '241', 'name' => 'Levite 2250cc Manzana x6'],
            ['code' => '242', 'name' => 'Levite 2250cc Pera x6'],
            ['code' => '243', 'name' => 'Levite 2250cc Mango  x6'],
            ['code' => '244', 'name' => 'Levite 1500cc Pomelo x6'],
            ['code' => '245', 'name' => 'Levite 1500cc Naranja x6'],
            ['code' => '246', 'name' => 'Levite 1500cc Manzana x6'],
            ['code' => '247', 'name' => 'Levite 1500cc Pera x6'],
            ['code' => '248', 'name' => 'Levite 1500cc Anana x6'],
            ['code' => '249', 'name' => 'Levite 1500cc Limonada'],
            ['code' => '250', 'name' => 'Levite 2000cc Pomelo x6'],
            ['code' => '251', 'name' => 'Levite 1650cc Limon Dulce'],
            ['code' => '252', 'name' => 'Levite 500cc Pomelo x 12'],
            ['code' => '253', 'name' => 'Levite 500cc Naranja x 12'],
            ['code' => '254', 'name' => 'Levite 500cc Manzana x 12'],
            ['code' => '255', 'name' => 'Hi-C Naranja x6'],
            ['code' => '256', 'name' => 'Brío 500cc Pomelo x12'],
            ['code' => '257', 'name' => 'Brío 500cc Naranja x12'],
            ['code' => '258', 'name' => 'Brío 500cc Manzana x12'],
            ['code' => '259', 'name' => 'Toallitas Humedas KIMBIES x30'],
            ['code' => '260', 'name' => 'Toallitas Humedas HUGGIES x12'],
            ['code' => '261', 'name' => 'Cunnington Pomelo 2250cc x6'],
            ['code' => '262', 'name' => 'Cunnington Pomelo Light 2250 x6'],
            ['code' => '263', 'name' => 'Cunnington Tonica 2250cc x 6'],
            ['code' => '264', 'name' => 'Cunnington Tonica Light 2250cc x 6'],
            ['code' => '265', 'name' => 'Cunnington Cola 2250cc x 6'],
            ['code' => '266', 'name' => 'Cunnington Cola Light 2250cc x6'],
            ['code' => '267', 'name' => 'Cunnington Naranja 2250cc x6'],
            ['code' => '268', 'name' => 'Cunnington Naranja Light 2250cc x6'],
            ['code' => '269', 'name' => 'Cunnington Lima 2250cc x6'],
            ['code' => '270', 'name' => 'Cunnington Lima Light 2250cc x6'],
            ['code' => '271', 'name' => 'Aquarius 2250cc Pomelo x6'],
            ['code' => '272', 'name' => 'Aquarius 2250cc Naranja'],
            ['code' => '273', 'name' => 'Aquarius 2250cc Manzana x6'],
            ['code' => '274', 'name' => 'Aquarius 2250cc Pera x6'],
            ['code' => '275', 'name' => 'Aquarius 2250cc Pomelo Rosado  x6'],
            ['code' => '276', 'name' => 'Aquarius 1500cc Pomelo x6'],
            ['code' => '277', 'name' => 'H2 OH! 1500cc x6 Manzana'],
            ['code' => '278', 'name' => 'H2 OH! 1500cc x6 Pomelo Rosado'],
            ['code' => '279', 'name' => 'H2 OH! 1500cc x6 Limoneto'],
            ['code' => '281', 'name' => 'SNACH SURTIDO X 25'],
            ['code' => '282', 'name' => 'Crush Pomelo 2250cc x6'],
            ['code' => '283', 'name' => 'Crush Naraja 2250cc x6'],
            ['code' => '284', 'name' => 'Crush Lima Limon 2250cc x6'],
            ['code' => '285', 'name' => 'RockStar 500cc x6'],
            ['code' => '286', 'name' => 'Patagonia Amber 710 x 6'],
            ['code' => '287', 'name' => 'Patagonia VERA Ipa 710 x6'],
            ['code' => '288', 'name' => 'Patagonia 24.7 Ipa  710 x6'],
            ['code' => '289', 'name' => 'Patagonia Hoppy 710 x 6'],
            ['code' => '290', 'name' => 'Patagonia Weisse 710 x6'],
            ['code' => '291', 'name' => 'Patagonia Bohemian 710 x6'],
            ['code' => '292', 'name' => 'Patagonia Lager del Sur 710 x6'],
            ['code' => '293', 'name' => 'Fernet Menta x6'],
            ['code' => '294', 'name' => 'Fernet Branca 450cc x12'],
            ['code' => '295', 'name' => 'Fernet Branca 750cc x12'],
            ['code' => '296', 'name' => 'Azucar Ledesma Rubio Mascabo x6'],
            ['code' => '297', 'name' => 'Pañales Huggies G x12'],
            ['code' => '298', 'name' => 'Pañales Huggies XG x12'],
            ['code' => '299', 'name' => 'Pañales Huggies XXG x12'],
            ['code' => '300', 'name' => 'YERBA Clasica 500gr x10'],
            ['code' => '301', 'name' => 'YERBA Tradicional 500gr x10'],
            ['code' => '302', 'name' => 'YERBA Premiun 500gr x10'],
            ['code' => '305', 'name' => 'Yerba Premiun 1kg x5'],
            ['code' => '306', 'name' => 'Lata Sidra 1930 DOLCE x24'],
            ['code' => '307', 'name' => 'Lata Sidra 1930 DEMI-SEC x24'],
            ['code' => '308', 'name' => 'Sidra 1888 500cc x 6'],
            ['code' => '309', 'name' => 'Sidra 1888 750cc x 6'],
            ['code' => '310', 'name' => 'Fresita x 6'],
            ['code' => '311', 'name' => 'Campari x 12'],
            ['code' => '312', 'name' => 'Speed XL 473cc S/AZUCAR X 12'],
            ['code' => '313', 'name' => 'Speed XL 473cc X 12'],
            ['code' => '314', 'name' => 'Speed x 24'],
            ['code' => '315', 'name' => 'Speed Chico S/AZUCAR x 24'],
            ['code' => '316', 'name' => 'Red Bull 250cc x24'],
            ['code' => '317', 'name' => 'Monster Negro  x6'],
            ['code' => '318', 'name' => 'Monster Paradise  x6 Verde'],
            ['code' => '319', 'name' => 'Monster Ultra  x6 Blanco'],
            ['code' => '320', 'name' => 'Monster Watermelon  x6 Rojo'],
            ['code' => '321', 'name' => 'Monster Mango Loco  x6'],
            ['code' => '322', 'name' => 'Monster Ultra The Doctor x6 Amarillo'],
            ['code' => '323', 'name' => 'Monster Ultra Sunrise x6 Naranja'],
            ['code' => '325', 'name' => 'Vino Familia Gascon Malbec x6'],
            ['code' => '326', 'name' => 'Vino Familia Gascon Cabernet x6'],
            ['code' => '327', 'name' => 'Vino D. V. Catena Cabernet/Malbec  x6'],
            ['code' => '328', 'name' => 'Vino Nampe Chenin Dulce  X6'],
            ['code' => '329', 'name' => 'Vino Circus Malbec x6'],
            ['code' => '330', 'name' => 'Vino Otro Loco Mas x 6'],
            ['code' => '359', 'name' => 'Vino Chacabuco Cabernet x6'],
            ['code' => '360', 'name' => 'Vino Chacabuco Rosado x6'],
            ['code' => '361', 'name' => 'Vino Chacabuco Chennin Dulce  x6'],
            ['code' => '362', 'name' => 'Vino UVITA Botellon x 6'],
            ['code' => '363', 'name' => 'Vino Finca Los Robles BOTELLON x6'],
            ['code' => '364', 'name' => 'Vino ANDELUNA Malbec x6'],
            ['code' => '365', 'name' => 'Vino ANDELUNA Cabernet x6'],
            ['code' => '366', 'name' => 'Vino ALTOS las HORMIGAS Malbec x6'],
            ['code' => '367', 'name' => 'Vino Tumpeter Malbec x6'],
            ['code' => '368', 'name' => 'Vino Tumpeter Malbec/Syrah x6'],
            ['code' => '369', 'name' => 'Vino Tumpeter Cabernet-Sauvignon  x6'],
            ['code' => '370', 'name' => 'Vino Tumpeter Cabernet Franck x6'],
            ['code' => '371', 'name' => 'Vino Tumpeter Chardonnay x6'],
            ['code' => '372', 'name' => 'Vino Tumpeter Syrah x6'],
            ['code' => '373', 'name' => 'Vino Tumpeter Merlot x6'],
            ['code' => '374', 'name' => 'Vino Tumpeter Sauvignon blanc x6'],
            ['code' => '376', 'name' => 'Vino Novecento Malbec x6'],
            ['code' => '377', 'name' => 'Vino Novecento Raíces Cabernet x6'],
            ['code' => '378', 'name' => 'Vino Novecento Raíces Blanco x6'],
            ['code' => '379', 'name' => 'Vino NICASIA Malbec x6'],
            ['code' => '380', 'name' => 'Vino Trapiche Reserva Malbec x6'],
            ['code' => '381', 'name' => 'Champagne Novecento Extra Dulce x6'],
            ['code' => '382', 'name' => 'Champagne Novecento Extra Brut x6'],
            ['code' => '383', 'name' => 'Champagne Federico A Extra Dulce  x6'],
            ['code' => '384', 'name' => 'Champagne Capricho x6'],
            ['code' => '385', 'name' => 'Champagne MUMM Extra Brut x6'],
            ['code' => '386', 'name' => 'Vino Escorihuela Malbec x6'],
            ['code' => '387', 'name' => 'Vino Escorihuela Cabernet  x6'],
            ['code' => '388', 'name' => 'Vino Nave Blend 750cc x6'],
            ['code' => '389', 'name' => 'Vino Viña Balbo 750cc  Tinto X6'],
            ['code' => '390', 'name' => 'Vino Viña de Balbo TInto 1.25cc x6'],
            ['code' => '391', 'name' => 'Vino Viña de Balbo Blanco 1.25cc x6'],
            ['code' => '392', 'name' => 'Vino Alma Mora Malbec x6'],
            ['code' => '393', 'name' => 'Vino Alma Mora Cabernet x 6'],
            ['code' => '395', 'name' => 'Vino Alma Mora  750cc Dulce Natural x 6'],
        ];

        $productData = [];
        foreach ($products as $product) {
            $productData[] = [
                'code' => $product['code'],
                'name' => $product['name'],
                'category_id' => 1, // Bebidas
                'brand_id' => 1, // Coca Cola
                'purchase_price' => 1000,
                'sale_price' => 1400,
                'active' => true,
                'tenant_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('products')->insert($productData);
    }
}
