<?php

namespace Database\Seeders;

use App\Models\ServiceType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ServiceTypeSeeder extends Seeder
{
    public function run()
    {
        /*
        // ==================== PARKING ====================
        DB::table('service_types')->insert([
            'name' => 'Estacionamiento Diurno',
            'description' => 'Estacionamiento por horas durante el día (6:00 - 20:00)',
            'base_price' => 3.50,
            'duration_minutes' => 60, // Precio por hora
            'time_unit' => 'hours',
            'min_units' => 1,
            'max_units' => 14, // Máximo 14 horas (6:00-20:00)
            'max_participants' => null,
            'requires_resource' => true,
            'resource_type_id' => 1, // Espacio de Parking
            'requires_capacity' => true,
            'max_capacity_per_reservation' => 5,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Estacionamiento Nocturno',
            'description' => 'Estacionamiento durante la noche (20:00 - 6:00)',
            'base_price' => 12.00,
            'duration_minutes' => 60,
            'time_unit' => 'hours',
            'min_units' => 1,
            'max_units' => 10, // Máximo 10 horas nocturnas
            'max_participants' => null,
            'requires_resource' => true,
            'resource_type_id' => 1,
            'requires_capacity' => true,
            'max_capacity_per_reservation' => 5,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Estacionamiento por Día Completo',
            'description' => 'Estacionamiento por 24 horas continuas',
            'base_price' => 25.00,
            'duration_minutes' => 1440, // 24 horas
            'time_unit' => 'days',
            'min_units' => 1,
            'max_units' => 30, // Máximo 30 días
            'max_participants' => null,
            'requires_resource' => true,
            'resource_type_id' => 1,
            'requires_capacity' => true,
            'max_capacity_per_reservation' => 5,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ==================== HOTELERÍA ====================
        DB::table('service_types')->insert([
            'name' => 'Habitación Individual - 1 Noche',
            'description' => 'Habitación individual con cama individual, baño privado',
            'base_price' => 89.00,
            'duration_minutes' => 1440, // 24 horas (1 noche)
            'time_unit' => 'days',
            'min_units' => 1,
            'max_units' => 30, // Máximo 30 noches
            'max_participants' => 1,
            'requires_resource' => true,
            'resource_type_id' => 2, // Habitación de Hotel
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Habitación Doble - 1 Noche',
            'description' => 'Habitación doble con cama queen size, baño privado',
            'base_price' => 129.00,
            'duration_minutes' => 1440,
            'time_unit' => 'days',
            'min_units' => 1,
            'max_units' => 30,
            'max_participants' => 2,
            'requires_resource' => true,
            'resource_type_id' => 2,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Suite Ejecutiva - 1 Noche',
            'description' => 'Suite de lujo con sala de estar y amenities premium',
            'base_price' => 199.00,
            'duration_minutes' => 1440,
            'time_unit' => 'days',
            'min_units' => 1,
            'max_units' => 30,
            'max_participants' => 2,
            'requires_resource' => true,
            'resource_type_id' => 2,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Habitación Familiar - 1 Noche',
            'description' => 'Habitación familiar con capacidad para 4 personas',
            'base_price' => 169.00,
            'duration_minutes' => 1440,
            'time_unit' => 'days',
            'min_units' => 1,
            'max_units' => 30,
            'max_participants' => 4,
            'requires_resource' => true,
            'resource_type_id' => 2,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // ==================== CONSULTORIO MÉDICO ====================
        DB::table('service_types')->insert([
            'name' => 'Consulta Médica General',
            'description' => 'Consulta con médico general, duración 30 minutos',
            'base_price' => 50.00,
            'duration_minutes' => 30,
            'time_unit' => 'minutes',
            'min_units' => 1,
            'max_units' => 2, // Máximo 1 hora
            'max_participants' => 1,
            'requires_resource' => true,
            'resource_type_id' => 3, // Consultorio Médico
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Consulta con Especialista',
            'description' => 'Consulta con médico especialista, duración 45 minutos',
            'base_price' => 80.00,
            'duration_minutes' => 45,
            'time_unit' => 'minutes',
            'min_units' => 1,
            'max_units' => 2,
            'max_participants' => 1,
            'requires_resource' => true,
            'resource_type_id' => 3,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Control de Rutina',
            'description' => 'Control médico de rutina, duración 20 minutos',
            'base_price' => 35.00,
            'duration_minutes' => 20,
            'time_unit' => 'minutes',
            'min_units' => 1,
            'max_units' => 1,
            'max_participants' => 1,
            'requires_resource' => true,
            'resource_type_id' => 3,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        DB::table('service_types')->insert([
            'name' => 'Examen Médico Completo',
            'description' => 'Examen médico completo con estudios, duración 90 minutos',
            'base_price' => 120.00,
            'duration_minutes' => 90,
            'time_unit' => 'minutes',
            'min_units' => 1,
            'max_units' => 1,
            'max_participants' => 1,
            'requires_resource' => true,
            'resource_type_id' => 3,
            'requires_capacity' => false,
            'max_capacity_per_reservation' => 1,
            'tenant_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);*/


        $serviceTypes = [
            // PELUQUERÍA CANINA
            [
                'name' => 'Baño Chico',
                'description' => 'Baño completo para raza chicas',
                'base_price' => 2500.00,
                'duration_minutes' => 60,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baño medio',
                'description' => 'Baño completo para raza medianas',
                'base_price' => 4500.00,
                'duration_minutes' => 90,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baño grande',
                'description' => 'Baño completo para raza grandes',
                'base_price' => 1800.00,
                'duration_minutes' => 120,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baño y corte chico',
                'description' => 'Baño completo y corte para raza chicas',
                'base_price' => 3200.00,
                'duration_minutes' => 60,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baño y corte medio',
                'description' => 'Baño completo y corte para raza medianas',
                'base_price' => 6800.00,
                'duration_minutes' => 90,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Baño y corte grande',
                'description' => 'Baño completo y corte para raza grandes',
                'base_price' => 6800.00,
                'duration_minutes' => 120,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // PELUQUERÍA HUMANA
            /*[
                'name' => 'Corte de Cabello Unisex',
                'description' => 'Corte profesional con lavado incluido y terminación a elección',
                'base_price' => 3500.00,
                'duration_minutes' => 45,
                'min_units' => 1,
                'max_units' => 2,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Coloración Completa',
                'description' => 'Tinte profesional con productos de primera calidad y baño de crema',
                'base_price' => 12000.00,
                'duration_minutes' => 120,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tratamiento Capilar',
                'description' => 'Tratamiento reconstructivo con keratina o botox capilar',
                'base_price' => 8500.00,
                'duration_minutes' => 90,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Peinado para Eventos',
                'description' => 'Peinado especial para bodas, fiestas o eventos importantes',
                'base_price' => 6000.00,
                'duration_minutes' => 60,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Manicura y Pedicura',
                'description' => 'Servicio completo de manicura y pedicura con esmaltado semipermanente',
                'base_price' => 4500.00,
                'duration_minutes' => 75,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // HOTELERÍA
            [
                'name' => 'Alojamiento Estándar',
                'description' => 'Habitación individual con baño privado y servicios básicos',
                'base_price' => 15000.00,
                'duration_minutes' => 1440, // 24 horas
                'min_units' => 1,
                'max_units' => 7,
                'max_participants' => 2,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Suite Ejecutiva',
                'description' => 'Suite amplia con sala de estar, minibar y amenities premium',
                'base_price' => 28000.00,
                'duration_minutes' => 1440,
                'min_units' => 1,
                'max_units' => 7,
                'max_participants' => 3,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Desayuno Buffet',
                'description' => 'Desayuno buffet completo con variedad de opciones dulces y saladas',
                'base_price' => 2500.00,
                'duration_minutes' => 60,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Limpieza Diaria',
                'description' => 'Servicio de limpieza y arreglo de habitación',
                'base_price' => 1500.00,
                'duration_minutes' => 30,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Servicio a la Habitación',
                'description' => 'Servicio de comida y bebidas en la habitación',
                'base_price' => 2000.00,
                'duration_minutes' => 45,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // PARKING
            [
                'name' => 'Estacionamiento por Hora',
                'description' => 'Servicio de estacionamiento vigilado por horas',
                'base_price' => 800.00,
                'duration_minutes' => 60,
                'min_units' => 1,
                'max_units' => 24,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Estacionamiento Diario',
                'description' => 'Estacionamiento por 24 horas con seguridad las 24hs',
                'base_price' => 5000.00,
                'duration_minutes' => 1440,
                'min_units' => 1,
                'max_units' => 7,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Estacionamiento Mensual',
                'description' => 'Abono mensual con lugar fijo y acceso las 24hs',
                'base_price' => 35000.00,
                'duration_minutes' => 43200, // 30 días
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lavado Express',
                'description' => 'Lavado exterior rápido mientras estaciona',
                'base_price' => 2500.00,
                'duration_minutes' => 30,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Valet Parking',
                'description' => 'Servicio de valet parking con estacionamiento y entrega del vehículo',
                'base_price' => 3000.00,
                'duration_minutes' => 15,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // CONSULTAS MÉDICAS
            [
                'name' => 'Consulta General',
                'description' => 'Consulta médica general con diagnóstico y recomendaciones',
                'base_price' => 6000.00,
                'duration_minutes' => 30,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Consulta Especializada',
                'description' => 'Consulta con médico especialista en área específica',
                'base_price' => 9500.00,
                'duration_minutes' => 45,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Control de Rutina',
                'description' => 'Control médico de seguimiento para pacientes en tratamiento',
                'base_price' => 4000.00,
                'duration_minutes' => 20,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Teleconsulta',
                'description' => 'Consulta médica virtual por videollamada',
                'base_price' => 5000.00,
                'duration_minutes' => 30,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Certificado Médico',
                'description' => 'Emisión de certificado médico laboral, deportivo o escolar',
                'base_price' => 3500.00,
                'duration_minutes' => 15,
                'min_units' => 1,
                'max_units' => 1,
                'max_participants' => 1,
                'requires_resource' => false,
                'resource_type_id' => null,
                'tenant_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],*/
        ];

        DB::table('service_types')->insert($serviceTypes);

        //$this->command->info('✅ 25 tipos de servicio creados exitosamente!');
        //$this->command->info('📋 Categorías: Peluquería Canina, Peluquería Humana, Hotelería, Parking, Consultas Médicas');

        //$this->command->info('Servicios creados: Parking (3), Hotel (4), Consultorio Médico (4)');
    }
}