/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./resources/js/components/ReservationForm copy 2.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Confirm: typeof import('./resources/js/components/dialogs/Confirm.vue')['default']
    ConfirmInput: typeof import('./resources/js/components/dialogs/ConfirmInput.vue')['default']
    ConfirmOptions: typeof import('./resources/js/components/dialogs/ConfirmOptions.vue')['default']
    ConfirmThreeButtons: typeof import('./resources/js/components/dialogs/ConfirmThreeButtons.vue')['default']
    copy: typeof import('./resources/js/components/ReservationForm copy.vue')['default']
    DateRangeField: typeof import('./resources/js/components/DateRangeField.vue')['default']
    DialogInfo: typeof import('./resources/js/components/dialogs/DialogInfo.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Filter: typeof import('./resources/js/components/Filter.vue')['default']
    FormClient: typeof import('./resources/js/components/dialogs/FormClient.vue')['default']
    FormCompleted: typeof import('./resources/js/components/dialogs/FormCompleted.vue')['default']
    FormConfirm: typeof import('./resources/js/components/dialogs/FormConfirm.vue')['default']
    FormValidate: typeof import('./resources/js/components/dialogs/FormValidate.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    PaymentsRow: typeof import('./resources/js/components/PaymentsRow.vue')['default']
    ReservationForm: typeof import('./resources/js/components/ReservationForm.vue')['default']
    'ReservationForm copy': typeof import('./resources/js/components/ReservationForm copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    Validate: typeof import('./resources/js/components/dialogs/Validate.vue')['default']
    VDatePicker: typeof import('./resources/js/components/VDatePicker.vue')['default']
    VDatetimePicker: typeof import('./resources/js/components/VDatetimePicker.vue')['default']
  }
}
