/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Confirm: typeof import('./resources/js/components/dialogs/Confirm.vue')['default']
    Confirmar: typeof import('./resources/js/components/dialogs/Confirmar.vue')['default']
    ConfirmarInput: typeof import('./resources/js/components/dialogs/ConfirmarInput.vue')['default']
    ConfirmarOptions: typeof import('./resources/js/components/dialogs/ConfirmarOptions.vue')['default']
    ConfirmInput: typeof import('./resources/js/components/dialogs/ConfirmInput.vue')['default']
    ConfirmOptions: typeof import('./resources/js/components/dialogs/ConfirmOptions.vue')['default']
    ConfirmThreeButtons: typeof import('./resources/js/components/dialogs/ConfirmThreeButtons.vue')['default']
    DateRangeField: typeof import('./resources/js/components/DateRangeField.vue')['default']
    DialogInfo: typeof import('./resources/js/components/dialogs/DialogInfo.vue')['default']
    DialogParteViewer: typeof import('./resources/js/components/dialogs/DialogParteViewer.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Filter: typeof import('./resources/js/components/Filter.vue')['default']
    FormClient: typeof import('./resources/js/components/dialogs/FormClient.vue')['default']
    FormCompleted: typeof import('./resources/js/components/dialogs/FormCompleted.vue')['default']
    FormConfirm: typeof import('./resources/js/components/dialogs/FormConfirm.vue')['default']
    FormConfirmar: typeof import('./resources/js/components/dialogs/FormConfirmar.vue')['default']
    FormValidate: typeof import('./resources/js/components/dialogs/FormValidate.vue')['default']
    Historial: typeof import('./resources/js/components/dialogs/Historial.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    PaymentsRow: typeof import('./resources/js/components/PaymentsRow.vue')['default']
    Reintentar: typeof import('./resources/js/components/dialogs/Reintentar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    Validate: typeof import('./resources/js/components/dialogs/Validate.vue')['default']
  }
}
