export const apiRoute = Object.freeze({

  /*companies:"api/companies",
  estados:"api/estados",
  clasificaciones:"api/clasificaciones",
  funciones:"api/funciones",
  personalPsa:"api/personalPsa",
  partes: "api/partes",*/
  tenants: "api/tenants",
  customers: "api/customers",
  products: "api/products",
  categories: "api/categories",
  brands: "api/brands",
  localities: "api/localities",
  roles: "api/roles",
  users: "api/users",
  warehouses: "api/warehouses",
  stocks: "api/stocks",
  statuses: "api/statuses",
  paymentMethods: "api/payment-methods",
  orders: "api/orders",
  payments: "api/payments",
  usersList: "api/users-list",
  ordersDelivery: "api/orders-delivery",
  ordersCustomersDelivery: "api/orders-customers-delivery",
  ordersSearch: "api/orders-search",
  ordersLatest: "api/orders-latest",
})
